name = "mini-commerce"
compatibility_date = "2024-05-10"
pages_build_output_dir = "public"

# --- Ikatan (Binding) Database D1 ---
# Ganti "DB_NAME_ANDA" dengan nama database D1 Anda di Cloudflare
[[d1_databases]]
binding = "DB"
database_name = "mini"
database_id = "7f40130d-20e3-4279-b57f-32b7e58e7b57"
